CREATE TABLE conserto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_entrada VARCHAR(255) NOT NULL,
    data_saida VARCHAR(255) NOT NULL,
    mecanico_nome VARCHAR(255) NOT NULL,
    mecanico_anos_de_experiencia INTEGER NOT NULL,
    veiculo_marca VARCHAR(255) NOT NULL,
    veiculo_modelo VARCHAR(255) NOT NULL,
    veiculo_ano INTEGER NOT NULL
);